global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'DemoEliteDesk'
    static_configs:
      - targets: ['192.168.40.93:9100']      

#  - job_name: 'dockerd-exporter'
#    dns_sd_configs:
#      - names:
#          - 'dockerd-exporter'
#        type: 'A'
#        port: 9323

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
          - 'node-exporter'
        type: 'A'
        port: 9100

 # - job_name: 'prometheus'
 #   dns_sd_configs:
 #     - names:
 #         - 'prometheus'
 #       type: 'A'
 #       port: 9090        
