global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

scrape_configs:
#  - job_name: 'prometheus-metrics'
#    metrics_path: '/prometheus/metrics'
#    static_configs:
#      - targets: ['localhost:9090']

  - job_name: 'DemoEliteDesk node-exporter'
    static_configs:
      - targets: ['192.168.40.93:9100']    

#  - job_name: 'RPI Grey node-exporter'
#    static_configs:
#      - targets: ['192.168.40.185:9100'] 

  - job_name: 'SNMP ONE2560'
    static_configs:
    - targets: ['192.168.40.51']
      labels:
        job: 'One2560'
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.40.51:9116  # The SNMP exporter's real hostname:port.     

#  - job_name: 'dockerd-exporter'
#    dns_sd_configs:
#      - names:
#          - 'dockerd-exporter'
#        type: 'A'
#        port: 9323

  - job_name: 'local node-exporter'
    dns_sd_configs:
      - names:
          - 'node-exporter'
        type: 'A'
        port: 9100     
